evolo_website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("web.urls",namespace="web"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from web.views import index,contact


app_name = "web"

urlpatterns = [
    path("",index,name="index"),
    path("contact/",contact,name="contact")
]

web/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models


INTERESTS=(
    ("1","Marketing"),
    ("2","Sales"),
    ("3","Designing")
)

class Customer(models.Model):
    logo = models.ImageField(upload_to="customers/")

    def __str__(self):
        return str(self.id)


class Service(models.Model):
    image = models.FileField(upload_to="services/")
    title = models.CharField(max_length=128)
    description = models.TextField()

    def __str__(self):
        return self.title


class Feature(models.Model):
    image = models.FileField(upload_to="features/")
    title = models.CharField(max_length=128)
    description = models.TextField(blank=True,null=True)
    list_items = ArrayField(models.CharField(max_length=200), blank=True,null=True)

    def __str__(self):
        return self.title


class Pricing(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField()
    price_in_dollar = models.IntegerField()
    feature_list = ArrayField(models.CharField(max_length=200),blank=True,null=True)
    not_feature_list = ArrayField(models.CharField(max_length=200),blank=True,null=True)

    def __str__(self):
        return self.title


class Contact(models.Model):
    full_name = models.CharField(max_length = 128)
    email = models.EmailField()
    phone = models.BigIntegerField()
    interested_in = models.CharField(max_length = 128,choices=INTERESTS)
    user_agreement = models.BooleanField()

    def __str__(self):
        return self.full_name


class Video(models.Model):
    image = models.FileField(upload_to="video/")

    def __str__(self):
        return str(self.id)


class Team(models.Model):
    image = models.FileField(upload_to="team-members/")
    name = models.CharField(max_length = 128)
    designation = models.CharField(max_length = 128)

    def __str__(self):
        return self.name

web/forms.py
from django.forms import ModelForm
from django import forms
from django.forms.widgets import EmailInput,Select,TextInput,NumberInput
from web.models import Contact
from web.models import INTERESTS

EMPTY_INTERESTS = (("","Interested in"),) + INTERESTS

class ContactForm(ModelForm):
    interested_in = forms.ChoiceField(choices = EMPTY_INTERESTS)

    class Meta:
        model = Contact
        fields = "__all__"
        widgets={
            "email":EmailInput(attrs={"placeholder":"Email"}),
            "full_name":TextInput(attrs={"placeholder":"Full name"}),
            "phone":NumberInput(attrs={"placeholder":"Phone"})
        }

web/views.py
import json
from django.shortcuts import render
from django.http.response import HttpResponse
from web.models import Customer,Service,Feature,Pricing,Contact,Video,Team
from web.forms import ContactForm


def index(request):
    customers = Customer.objects.all()
    services = Service.objects.all()
    features = Feature.objects.all()
    pricings = Pricing.objects.all()
    videos = Video.objects.all()[:1]
    team_members = Team.objects.all()

    form = ContactForm()

    context={
        "customers" : customers,
        "services" : services,
        "features" : features,
        "pricings" : pricings,
        "form" : form,
        "videos" : videos,
        "team_members" : team_members
    }
    
    return render(request,"index.html",context=context)


def contact(request):
    form = ContactForm(request.POST)
    if form.is_valid():
        
        email = request.POST.get("email")

        if not Contact.objects.filter(email=email).exists():
            form.save()
            response_data = {
                "status" : "success",
                "title" : "Successfully Registered",
                "message" : "You subscribed to our newsletter successfully"
            }
        else:
            response_data = {
                "status" : "error",
                "title" : "You are already registered",
                "message" : "You are already a member. No need to register again."
            }
    else:
        response_data = {
            "status" : "error",
            "title" : "Invalid data",
            "message" : "Please enter valid data."
        }

    return HttpResponse(json.dumps(response_data), content_type = "application/javascript")

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <title>Evolo</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'css/fontello.css' %}" type="text/css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"/>

        <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="{% static 'images/favicon.png' %}"
        />

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta property="og:image" content="" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
    </head>
    <body>
        <header>
            <h1 class="left">
                <a href="#"><img src="{% static 'images/logo.svg' %}" alt="Logo" /></a>
            </h1>
            <nav class="right">
                <ul>       
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Pricing</a></li>
                    <li><a href="#">Request</a></li>
                    <li><a href="#">About<i class="fas fa-caret-down"></i></a></li>
                    <li><a href="#">Contact</a></li>   
                    <li>
                        <span class="icons">
                            <a href="#"><img src="{% static 'images/facebook.png' %}" alt="facebook" style="width:20px" /></a>
                            <a href="#"><img src="{% static 'images/twitter.png' %}" alt="twitter" style="width:20px" /></a>
                        </span>
                    </li>          
                </ul>
            </nav>
            <img class="background" src="{% static 'images/header-background.jpg' %}" alt="" />
        </header>
        {% block content %}

        {% endblock %}
        <section id="footer">
            <section class="wrapper">
                <div class="top">
                    <div class="item">
                        <h4>About Evolo</h4>
                        <p>We're passionate about offering some of the best business growth services for startups</p>
                    </div>
                    <div class="item">
                        <h4>Important Links </h4>
                        <ul>
                            <li>
                                <p>Our business partners <a href="#">startuguide.com</a></p>
                            </li>
                            <li>
                                <p>Read our <a href="#">Terms & Conditions. </a><a href="#">Privacy Policy</a></p>
                            </li>
                        </ul>
                    </div>
                    <div class="item">
                        <h4>Social Media</h4>
                        <img src="{% static 'images/facebook.png' %}" alt="facebook">
                        <img src="{% static 'images/twitter.png' %}" alt="twitter">
                        <img src="{% static 'images/google-plus.png' %}" alt="google-plus">
                        <img src="{% static 'images/instagram.png' %}" alt="instagram">
                        <img src="{% static 'images/linkedin.png' %}" alt="linkedin">
                    </div>
                </div>
                <div class="bottom">
                    <small>Copyright &copy;2021 - All rights reserved</small>
                </div>
            </section>
        </section>

        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'js/sweetalert2.min.js' %}"></script>
        <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>

templates/index.html
{% extends "base.html" %} 
{% load static %}

{% block content %}
    <section id="spotlight" class="wrapper flex-wrapper">
            <section class="content">
                <h1><span>StartUp Landing </span><br/>Page Template Free</h1>
                <p>Use Evolo free landing page template to promote your business startup and generate leads for the offered services.</p>
                <a href="#" class='button'>DISCOVER</a>
            </section>
            <section class="right_container">
                <div class="image_container">
                    
                    <img class="teamwork" src="{% static 'images/header-teamwork.svg' %}" alt="" /> 
                </div>
            </section>           
    </section> <!-- section#spotlight -->

    <section id="customers">
        <section class="wrapper">
            <p>Trusted By</p>
            <ul>
                {% for customer in customers %}
                    <li><a href="#"><img src="{{customer.logo.url}}" alt="logo" /></a></li>
                {% endfor %}
            </ul>
        </section>
    </section> <!-- section#customers -->

    <section id="services">
        <section class="wrapper">
            <h2>Business Growth Services</h2>
            <p>We serve small and medium sized companies in all tech related industries with high quality growth services which are presented below.</p>
            <ul>
                {% for service in services %}
                <li>
                    <img src="{{service.image.url}}" alt=""/>
                    <h3>{{service.title}}</h3>
                    <p>{{service.description}}</p>
                </li>
                {% endfor %}
            </ul>
        </section>
    </section> <!-- section#services -->

    <section id="features">
        <section class="wrapper">
            {% for feature in features %}
                <section class="item">
                    <div class="content">
                        <h2>{{feature.title}}</h2>
                        <p>{{feature.description}} </p>
                        <ul>
                            {% for item in feature.list_items %}
                                <li>
                                    <img src="{% static 'images/check.png' %}" alt=""/>
                                    <p>{{item}}</p>
                                </li>
                            {% endfor %}
                        </ul>
                        <a href="#" class="button">LIGHTBOX</a>
                    </div>
                    <div class="image_container">
                        <img src="{{feature.image.url}}" alt="">
                    </div>
                </section>
            {% endfor %}
        </section>
    </section> <!-- section#features -->

    <section id="pricing">
        <section class="wrapper">
            <h2>Multiple Pricing Options</h2>
            <p>We've prepared pricing plans for all budgets so you can started right away. They're great for small companies and large organizations. </p>
            <ul>
                {% for price in pricings %}
                <li>
                    <h3>{{price.title}}</h3>
                    <p>{{price.description}}</p>   
                    <div class="price">
                        <span>&#36;</span><h1>{{price.price_in_dollar}}</h1>
                        <label>Monthly</label>
                    </div>                                                       
                    <ul>
                        {% for item in price.feature_list %}
                        <li>
                            <img src="{% static 'images/check.png' %}" alt="check">
                            <span>{{item}}</span>
                        </li>
                        {% endfor %}
                        
                        {% for item in price.not_feature_list %}
                        <li>
                            <img src="{% static 'images/cancel.png' %}" class="cancel" alt="cancel">
                            <span>{{item}}</span>
                        </li>
                        {% endfor %}
                    </ul>
                    <a href="#" class="button">REQUEST</a>
                </li>
                {% endfor %}
            </ul>
        </section>
    </section>  <!-- section#pricing -->

    <section id="contact">
        <section class="wrapper">
            <div class="left">
                <h3>Fill The Following Form To Request A Meeting</h3>
                <p>Evolo is one of the easiest and feature acked marketing automation apps in the market. Discover what it can do for your business organization right away.</p>
                <ul>
                    <li>
                        <img src="{% static 'images/check.png' %}" alt="check"/>
                        <p><span>Automate your marketing </span>activities and get results today</p>
                    </li>
                    <li>
                        <img src="{% static 'images/check.png' %}" alt="check"/>
                        <p><span>Interact with all your </span>targeted customers at a personal level</p>
                    </li>
                    <li>
                        <img src="{% static 'images/check.png' %}" alt="check"/>
                        <p><span>Convince them to buy </span>your company's awesome products</p>
                    </li>
                    <li>
                        <img src="{% static 'images/check.png' %}" alt="check"/>
                        <p><span>Save precious time </span>and invest it where you need it the most</p>
                    </li>
                </ul> 
            </div>
            <div class="right">
                <form action="{% url 'web:contact' %}" method="POST" class="ajax">
                        {% csrf_token %}
                        <div class="input">{{form.full_name}}</div>
                        <div class="input">{{form.email}}</div>                       
                        <div class="input">{{form.phone}}</div>
                        <div class="input">{{form.interested_in}}</div>
                        <div class="full checkbox">
                            {{form.user_agreement}}
                            <label for="{{form.user_agreement.id_for_label}}">I agree with Evolo's stated <a href="#">Privacy Policy</a> and <a href="#">Terms & Conditions</a> </label>
                        </div>
                        <div class="full">
                            <input class="submit" type="submit" value="REQUEST" />
                        </div>
                </form>
            </div>
        </section>
    </section> <!-- section#contact -->

    <section id="video">
        <section class="wrapper">
            <h2>Check Out The Video</h2>
            {% for video in videos %}
            <div class="video-frame">
                <img src="{{video.image.url}}" alt="video" class="main-image">
                <img src="{% static 'images/play.svg' %}" alt="play" class="play">
            </div>        
            {% endfor %}
            <p>The video will show you a case study for one of our <span>Major Customers </span>and will help you understand why your startup needs Evolo in this highly competitive market.</p>
        </section>
    </section> <!-- section#video -->

    <section id="team-members">
        <section class="wrapper">
            <div class="top">
                <h2>About The Team</h2>
                <p>Meat our team of specialized marketers and business developers which will help you research new products and launch them in new emerging markets.</p>
            </div>
            <div class="bottom">
                <ul>
                    {% for member in team_members %}
                    <li>
                        <img src="{{member.image.url}}" alt="{{member.name}}">
                        <h3>{{member.name}}</h3>
                        <p>{{member.designation}}</p>
                        <div class="social-icons">
                            <img src="{% static 'images/facebook.png' %}" alt="facebook">
                            <img src="{% static 'images/twitter.png' %}" alt="twitter">
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
    </section> <!-- section#team-members -->

{% endblock %}